#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Tue Oct 21 03:31:21 PM CEST 2025
@author: sarkarjj
@hostname: hydra2

DESCRIPTION
- This module generates the flat field for removing contaminant patches.
- Images are aligned and median stack is taken based on reference frame.
- Flat is generated by dividing sun image by median stacked image.
- This is tested for sun-at-center images.
- Align images by cross-correlation for feature rich bands.
- Align images by sun-cent information for continua.
"""
import os
import sys
import glob
import numpy as np
import astropy.units as u
from astropy.io import fits
import matplotlib.pyplot as plt
from sunpy.map import Map, MapSequence
from astropy.coordinates import SkyCoord, SkyOffsetFrame
from sunkit_image.coalignment import calculate_match_template_shift, apply_shifts

def get_submap(ref_img):
	"""
	Get a submap from the reference image for template matching.
	Parameters:
	- ref_img: Reference SunPy map image.
	Returns:
	- Submap of the reference image.
	"""
	center_coord = SkyCoord(0 * u.arcsec, 950* u.arcsec, frame=ref_img.coordinate_frame) #54,157
	width = 1100 * u.arcsec
	height =300 * u.arcsec   
	offset_frame = SkyOffsetFrame(origin=center_coord, rotation=0*u.deg)
	rectangle = SkyCoord(lon=[-1/2, 1/2] * width, lat=[-1/2, 1/2] * height, frame=offset_frame)
	ref_submap = ref_img.submap(rectangle) #bottom_left, top_right=top_right)
	return ref_submap

def clean_line_channels(files, template_map):
    """
    - To process images taken in the line channels
    NB03, NB04 and NB08
    """
    ref_submap = get_submap(template_map)
    ref_cdel=ref_submap.meta['CDELT1']
    seq = Map(files, sequence=True)
    align_shift = calculate_match_template_shift(seq, template=ref_submap)
    shift_xPix = align_shift['x'].value / ref_cdel * -1
    shift_yPix = align_shift['y'].value / ref_cdel * -1
    aligned_maps = apply_shifts(seq, yshift=shift_yPix * u.pixel, xshift=shift_xPix * u.pixel, clip=False)
    aligned_map_arr= np.stack([m.data for m in aligned_maps], axis=0)
    med= np.median(aligned_map_arr, axis=0)
    flat_frame= template_map.data/med
    return (flat_frame)

def clean_contt_channels(files):
    """
    - Process the images to generate a flat field of 
    the contaminant patterns.
    - Remove the contaminant patterns from the images.
    INPUT:
        files: list of filepaths
        tp: template filepath
    OUTPUT:
        corrected_image_map: SunPy map of the corrected data.
        flat_field: contamination flat field.
    """
    seq = Map(files, sequence=True)
    map_arr= np.stack([m.data for m in seq], axis=0)
    raw_med= np.median(map_arr, axis=0)
    x_arry=[template_map.meta['CRPIX1']-m.meta['CRPIX1'] for i, m in enumerate(seq)]
    y_arry=[template_map.meta['CRPIX2']-m.meta['CRPIX2'] for i, m in enumerate(seq)]
    aligned_maps = apply_shifts(seq, yshift= y_arry * u.pixel, xshift=x_arry * u.pixel, clip=False)
    aligned_imgs= np.stack([m.data for m in aligned_maps], axis=0)
    med= np.median(aligned_imgs, axis=0)
    med[med==0]=1
    flat_frame= raw_med/med
    return (flat_frame)

def roi_correction(roi_files,roi_flat):
    roi_seq= Map(roi_files, sequence=True)
    for i, m in enumerate(roi_seq):
        corrected_img_data= m.data/roi_flat
        corrected_img_data= np.nan_to_num(corrected_img_data, nan=0.0)
        corrected_map= Map(corrected_img_data, m.meta)
        SAVE and savefiles(m.meta['F_NAME'], corrected_map, roi_flat)
    return corrected_map

def visualize(map1, flatframe, map3):
    """
    DESCRIPTION:
    See a preview of the individual images.
    INPUT:
    - map1, map3: Sunpy Map
    - flatframe: numpy 2D array
    RETURNS: Visualization.
    """
    fig, ax= plt.subplots(1,3, sharex=True, sharey=True)
    im0= ax[0].imshow(map1.data, origin='lower', vmin=VMN, vmax=VMX)
    ax[0].set_title('Raw')
    plt.colorbar(im0, ax=ax[0])
    im1= ax[1].imshow(flatframe, origin='lower', vmin=VMN, vmax=1.2)
    ax[1].set_title('Calibration frame')
    plt.colorbar(im1, ax=ax[1])
    im2= ax[2].imshow(map3.data, origin='lower', vmin=VMN, vmax=VMX)
    ax[2].set_title('Corrected map')
    plt.colorbar(im2, ax=ax[2])
    plt.show()

def savefiles(file, corrected_image_map, flat_field, FLAT=False):
    img_savepath= os.path.join(project_path, f'products/roi/{file}')
    corrected_image_map.save(img_savepath, overwrite=True)
    print("saved as", file)
    if FLAT:
        flat_savepath= os.path.join(project_path, f'data/interim/flat_{os.path.basename(file)}')
        fits.writeto(flat_savepath, flat_field, overwrite=True)
        print("Flat frame saved as", flat_savepath)

if __name__=='__main__':
    SAVE= True # Toggle to save corrected image
    PLOT= True # Toggle to turn off visualization
    LIM= 20 # Max no. of images to be used for the stack and processed
    project_path= os.path.abspath('..')
    files= sorted(glob.glob(os.path.join(project_path, f'data/raw/full_disk/*.fits'))) # Filepath for full disk images
    roi_files= sorted(glob.glob(os.path.join(project_path, f'data/raw/roi/*.fits')))
    
    print("Generating flat field image from")
    template_file_index= len(files)//2
    if len(files)>LIM: # Stop execution if num of files is more than LIM
        print(f'Stopping execution. \nMore than {LIM} files queued')
        sys.exit()
    template_map= Map(files[template_file_index]) #Middle of the stack taken as reference
    ftr_name= template_map.meta['FTR_NAME']
    if ftr_name not in ['NB03','NB04','NB08']:
        print(os.path.basename(files[template_file_index]))
        flat_field= clean_contt_channels(files)
    elif ftr_name in ['NB03','NB04','NB08']:  
        print(os.path.basename(files[template_file_index]))
        for file in files: # use each image as template for better alignment
            template_map=Map(file)
            flat_field= clean_line_channels(files, template_map)
    else:
       print('Check file metadata. FTR_NAME mismatch')
    
    roi_map= Map(roi_files[0])
    col, row= roi_map.meta['X1'], roi_map.meta['Y1']
    s_row, s_col= roi_map.meta['NAXIS1'], roi_map.meta['NAXIS2']
    roi_flat= flat_field [row:row+s_row, col-20:col+s_col-20]
    roi_cleaned_map= roi_correction(roi_files, roi_flat)
    if PLOT:
        VMN, VMX= 0, 2.5e4
        visualize(roi_map, roi_flat, roi_cleaned_map)
